db_config:
  engine: PDO

# To setup a sqlite connection:
#  provider: sqlite
#  username: root
#  password: test
#  database: file.txt
---
# To setup a mysql connection:
#  provider: mysql
#  hostname: localhost
#  username: root
#  password: 
#  database: database
---
# To setup a postgresql connection:
#  provider: mysql
#  hostname: localhost
#  username: root
#  password: 
#  database: database